# Generated by Django 3.1.3 on 2020-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Reservation code'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('accepted', 'Potwierdzona'), ('cancelled', 'Anulowana'), ('finished', 'Zakończona')], default='pending', max_length=20),
        ),
    ]
